## Introduction to tensorflow

- Tensor flow is the open source machine learning library designed by the Google brain team. It is designed to build the machine learning model.

In [2]:
import tensorflow as tf
print(tf.__version__)

2.16.2


creation of a tensor

In [4]:
a=tf.constant([1,2,3])
b=tf.constant([4,5,6])

print(a)
print(b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [7]:
print(tf.add(a,b)) 
print(tf.multiply(a,b) )

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


Random tensor

In [22]:
random_tensor=tf.random.normal((3,4),mean=10.0)

In [23]:
random_tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[11.306964 ,  9.747722 ,  6.4928207,  8.465839 ],
       [ 8.44576  ,  8.239226 ,  8.314192 ,  8.7464485],
       [ 9.498787 ,  8.838983 ,  9.829343 ,  9.090591 ]], dtype=float32)>